version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_blackjack
    restart: always
    ports:
      - "27017:27017" # ใช้ port มาตรฐาน
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=appdb55 # ตรงกับ .env

volumes:
  mongodb_data:
